config/routes.rb
Rails.application.routes.draw do

  root 'users#new'
  get '/home' => 'home#index'
  resource :users, only: [:new, :create]

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  namespace :api, defaults: {format: :json} do
    get 'tweets' => 'tweets#index'
    resources :posts
    resources :comments
  end

end

app/views/shared/_footer.html.erb
_footer.html.erb

app/views/shared/_header.html.erb
<header ng-class="{true: 'body-pushed'}[main.pushmenu]">

		<nav class="navbar navbar-default navbar-fixed-top ">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <a class="navbar-brand" href="#">
		        
		       <%= image_tag src="favicon2.jpg", width: '30px', height: '30px' %>

		       <h6 id="pharmatalk">pharmaTalk</h6>
		       <!-- <a> Get industry info. Stay connected. Be in the know.</a> -->

		       <% if logged_in? %>

				<button ng-click="cookie.remove()"><%= link_to "Logout", logout_path, method: "delete" %> </button>
				<!-- display post link option -->

		      <!--  <a href="#" class="glyphicon glyphicon-edit" data-toggle="modal" data-target="#post-link"></a> -->

		       <!-- display hamburger menu -->
		       <% end %>
		       <!-- <a href="#" class="glyphicon glyphicon-menu-hamburger" ng-click="main.pushmenu = !main.pushmenu"></a> -->
		       
		       </a>
		    </div>
		  </div>
		</nav>	
</header>

app/views/shared/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="loginLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="loginLabel">Login</h4>
      </div>

      
        <%= form_for(:session, url: login_path) do |f| %>
        
        <div class="modal-body">

            <%= f.email_field :email, class: 'form-control', autofocus: 'true', placeholder: "Email" %>

            <br />

            <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>

            
        </div>

        <div class="modal-footer">
          
          <%= f.submit "Log in", class: 'btn btn-md btn-success' %>

        </div>

        <% end %>

    
    </div>
  </div>
</div>

<script type="text/javascript">
  // When doc loads
    $(function(){

      // jQuery for modal
      $("#login").on('shown.bs.modal', function(){
        $(this).find("[autofocus]:first").focus();
      });


    });
</script>

app/views/shared/_sidemodal.html.erb
<!-- hamburger menu that shows up as a pop up modal are to Log Out -->



<div class="modal fade" id="hamburger" tabindex="-1" role="dialog" aria-labelledby="signupLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="hamburger">Menu</h4>
      </div>
	
	
	<div class="col-xs-12" ng-controller="cookieController as cookie">

		<% if logged_in? %>

			<button ng-click="cookie.remove()"><%= link_to "Logout", logout_path, method: "delete" %> </button>
		<% else %>

			<button data-toggle="modal" data-target="#login">Log in</button>
		<% end %>
		
	</div>
	
</nav>

<script type="text/javascript">
  // When doc loads
    $(function(){

      // jQuery for modal
      $("#hamburger").on('shown.bs.modal', function(){
        $(this).find("[autofocus]:first").focus();
      });


    });
</script>

app/views/shared/_signupmodal.html.erb
<!-- Modal to Sign Up -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog" aria-labelledby="signupLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="signupLabel">Sign Up</h4>
      </div>

      
        <%= form_for @user do |f| %>
        
        <div class="modal-body">

        	<%= f.text_field :name, class: 'form-control', autofocus: 'true', placeholder: "Name" %>

            <br />

            <%= f.email_field :email, class: 'form-control', autofocus: 'true', placeholder: "Email" %>

            <br />

            <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>

            <br />

            <%= f.password_field :password, class: 'form-control', placeholder: 'Password Confirmation' %>

            
        </div>

        <div class="modal-footer">
          
          <%= f.submit "Sign Up", class: 'btn btn-md btn-success' %>

        </div>

        <% end %>

    
    </div>
  </div>
</div>

<script type="text/javascript">
  // When doc loads
    $(function(){

      // jQuery for modal
      $("#signup").on('shown.bs.modal', function(){
        $(this).find("[autofocus]:first").focus();
      });


    });
</script>